version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - yasukexxx
  - autumo
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.0
    - 1.37.1
    - 1.37.10
    - 1.37.11
    - 1.37.12
    - 1.37.13
    - 1.37.14
    - 1.37.15
    - 1.37.16
    - 1.37.17
    - 1.37.18
    - 1.37.19
    - 1.37.20
    - 1.37.21
    - 1.37.22
    - 1.37.23
    - 1.37.24
    - 1.37.25
    - 1.37.27
    - 1.37.28
    - 1.37.29
    - 1.37.3
    - 1.37.30
    - 1.37.31
    - 1.37.32
    - 1.37.33
    - 1.37.4
    - 1.37.6
    - 1.37.8
    - 1.37.9
    - 1.38.0
    - 1.38.1
    - 1.38.11
    - 1.38.14
    - 1.38.16
    - 1.38.2
    - 1.38.27
    - 1.38.3
    - 1.38.4
    - 1.38.5
    - 1.38.7
    - 1.38.8
    - 1.38.9
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.3
    - 0.20.4
    - 0.20.5
    - 0.21.0
  - dependency-name: k8s.io/api
    versions:
    - 0.20.3
    - 0.20.5
    - 0.21.0
  - dependency-name: k8s.io/client-go
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
  - dependency-name: sigs.k8s.io/kustomize/api
    versions:
    - 0.7.4
    - 0.8.0
    - 0.8.1
    - 0.8.2
    - 0.8.4
